module.exports = {
  USER_ROLES: {
    USER: "user",
    ADMIN: "admin",
    SERVICE_PROVIDER: "service_provider"
  },
  COUPON_TYPE: {
    PERCENTAGE: "PERCENTAGE",
    FLAT_VALUE: "FLAT_VALUE",
  },
  BOOKING_STATUS: {
    PLACED: "PLACED",
    ACCEPTED: "ACCEPTED",
    ONGOING: "ONGOING",
    CLOSED: "CLOSED",
    CANCELLED: "CANCELLED"
  },
  BOOKING_REQUEST_STATUS: {
    ACCEPTED: "ACCEPTED",
    REJECTED: "REJECTED"
  },
  PAYMENT_STATUS: {
    PAID: "PAID",
    NOT_PAID: "NOT_PAID"
  },
  LEAVE_STATUS: {
    PENDING: "PENDING",
    APPROVED: "APPROVED",
    REJECTED: "REJECTED",
    CANCELLED: "CANCELLED"
  },
  SERVICE_PROVIDER_STATUS: {
    ACTIVE: "ACTIVE",
    INACTIVE: "INACTIVE"
  },
  REDEEM_REQUEST_STATUS:{
    PENDING: "PENDING",
    CLOSED: "CLOSED",
    CANCELLED: "CANCELLED"
  }
};
